sudo: required
dist: trusty
language: node_js
node_js:
  - "7"
  - "8"
script:
   - npm run ci
notifications:
  irc: "irc.freenode.org#brass-monkey"
branches:
  only:
    - master
    - /^greenkeeper/.*$/
