# Javascript Node CircleCI 2.1 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.1

commands:
  test-nodejs:
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: npm ci

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run: npm run ci

jobs:
  node10:
    docker:
      - image: circleci/node:10
    steps:
      - test-nodejs

  node12:
    docker:
      - image: circleci/node:12
    steps:
      - test-nodejs

workflows:
  version: 2
  test_node_versions:
    jobs:
      - node10:
        filters:
          branches:
            ignore:
              - gh-pages
      - node12:
        filters:
          branches:
            ignore:
              - gh-pages
